###Lista de users
GET http://localhost:3000/contas

###Get user
GET http://localhost:3000/contas/4d5f2422-71aa-4b5c-98e8-062ca0d75fa0

###Criar user
POST http://localhost:3000/contas
Content-Type: application/json

{
  "name": "Teste1",
  "cpf": "12345678902",
  "email": "teste1@example.com",
  "phone": "+5511999999999",
  "address": "Rua Teste, 123, São Paulo, SP"
}  

###Atualizar user
PATCH http://localhost:3000/contas/ac787374-dd8f-478a-aed5-861de7ac4850
Content-Type: application/json

{
  "name": "Teste2",
  "email": "teste2@example.com",
  "phone": "+5511999999999",
  "address": "Rua Teste, 123, São Paulo, SP"
} 
###Deletar user
DELETE http://localhost:3000/contas/4d5f2422-71aa-4b5c-98e8-062ca0d75fa0